### ISSUE TITLE
Linux On Surface versehentlich auf Linux MX installiert

### ISSUE THREAD

**Issue by schnoepsel** [actionschnitzel/linux_debs_to_go#1]
Ich bin noch neu bei Linux und dachte, ich kann Linux On Surface auf Linux MX installieren, um Extras zu erhalten.
Dabei kam es zu Installationsfehlern und -Verweigerungen. Muss ich Linux On Surface wieder deinstallieren oder kann ich neu starten und alles bleibt beim Alten. Freue mich auf Hilfe.

**Comment by actionschnitzel** [comment]
Hi,

GitHub ist nicht unbedingt der beste Ort, um eine Lösung zu finden. Dieses Repository ist auch nur eine Zusammenstellung von allem, was ich benötige.  
Wenn du Probleme mit deinem Surface hast, wäre es besser, wenn du das z.B. im [Linux Guides Forum](https://forum.linuxguides.de/) vorträgst.  
Da könnte man das genauer besprechen und auch analysieren.

GitHub-Issues sind eher dafür da, Fehler im Code des betreffenden Repos anzusprechen.

LG
